### ISSUE TITLE
Play clients depend on global state

### ISSUE THREAD

**Issue by fiadliel** [apicollective/apibuilder#434]
`play.api.libs.ws.WS.url` and `play.api.libs.ws.WS.client` depend on global state, i.e. that an `Application` has been started.

This prevents using the `WS` client API in eagerly initialised code (i.e. code that starts up before any HTTP requests are made, marked as eager singletons).

The recommended way of doing this with Play is with Guice, e.g. `class MyService @Inject() (ws: WSClient)`

Example stack trace:

```
java.lang.RuntimeException: There is no started application
    at scala.sys.package$.error(package.scala:27) ~[scala-library-2.11.8.jar:na]
    at play.api.Play$$anonfun$current$1.apply(Play.scala:71) ~[play_2.11-2.4.6.jar:2.4.6]
    at play.api.Play$$anonfun$current$1.apply(Play.scala:71) ~[play_2.11-2.4.6.jar:2.4.6]
    at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.8.jar:na]
    at play.api.Play$.current(Play.scala:71) ~[play_2.11-2.4.6.jar:2.4.6]
    at Client._requestHolder(XXXX:yyy) ~[classes/:na]
    at Client._executeRequest(XXXX:yyy) ~[classes/:na]
    at Client$ZZZ$.get(XXXX:yyy) ~[classes/:na]
```

**Comment by mbryzek** [comment]
Thanks Gary. Are you okay if we make this change globally for say the 2.4 x client - will that be okay (it will be a small but breaking change)?

**Comment by fiadliel** [comment]
I don't think there are many other options, it seems reasonable to try and avoid extra proliferation of clients. The breaking change is unfortunate, but is probably the correct thing to do.

**Comment by fiadliel** [comment]
Whether you want to include `@Inject` yourself, or request that a WS client be passed in by the user, i think whichever feels best to you. It feels like leaving that up to the user of the apidoc client is best, but that's a hazy opinion.

**Comment by mbryzek** [comment]
Since play is going the route of guice - what would you think if:

  a. we make the breaking chance in play 2.4 clients to use DI
  b. we note that people who don't like this can use the ning client instead (it is API compatible)
  c. if it becomes a problem, we add a new play 2.4.x client that accepts ws as a parameter

**Comment by fiadliel** [comment]
That sounds acceptable (of course, depending on javax.inject rather than anything Guice-specific).

**Comment by gheine** [comment]
I believe this has long been fixed
