### ISSUE TITLE
Scala ADT encoding improvements

### ISSUE THREAD

**Issue by fiadliel** [apicollective/apibuilder#521]
For best practice with Scala ADTS:

- All case class definitions should be marked as `final` to avoid subclassing
- ADT trait should be marked `extends Product with Serializable`
  The reason for this is that the calculated LUB for the subtypes is not just the trait, due to the extra code mixed in by `case class` or `case object`. We want the inferred type to be just the trait, this especially helps when using code which has invariant type parameters.

**Comment by ChengGit** [comment]
Hi @mbryzek and @fiadliel,
I do totally agree with this improvement, however my mockito-based tests start encountering one issue after this the PR(https://github.com/apicollective/apibuilder-generator/pull/399): 

```
org.mockito.exceptions.base.MockitoException: Cannot mock/spy class com.gilt.checkout.api.v0.models.CheckoutSession
[info] Mockito cannot mock/spy following:
[info]   - final classes
[info]   - anonymous classes
[info]   - primitive types
[info]   at org.scalatest.mock.MockitoSugar$class.mock(MockitoSugar.scala:74)
```

Basically it is saying mockito cannot mock final case classes.
Would you like to give some suggestions in general when dealing with applications utilizing both api-builder and mockito library?

Thanks in advance,
Cheng

**Comment by fiadliel** [comment]
Making case classes final is best practice, for many reasons.

Some people discuss this issue at https://stackoverflow.com/questions/37184528/mock-case-class-in-scala-mockito

In general, these case classes model data. Data doesn't need to be mocked, it just is (you can create a value at any time). You probably want to be looking at the interfaces that return data, and perhaps mocking them instead.

**Comment by ChengGit** [comment]
yea I like the idea that case class should be final, thanks for the explanations @fiadliel !

**Comment by kubukoz** [comment]
Hi, I think this is solved by https://github.com/apicollective/apibuilder-generator/pull/399 and can be closed now ;)

**Comment by kubukoz** [comment]
(ignore previous comment)

**Comment by mbryzek** [comment]
case classes are final - closing issue
