### ISSUE TITLE
Renamed Postgresql docker image does not exist

### ISSUE THREAD

**Issue by fabiocognigni** [apicollective/apibuilder#647]
The command in the [DEVELOPER guide](https://github.com/apicollective/apibuilder/blob/master/DEVELOPER.md#developing) to run Postgresql locally via Docker doesn't work: `apicollective/apibuilder-postgresql` doesn't exist in DockerHub but `flowcommerce/apibuilder-postgresql` does.

**Comment by mbryzek** [comment]
fixed in https://github.com/apicollective/apibuilder/pull/649

**Comment by fabiocognigni** [comment]
@mbryzek I just noticed that the `api` fails when run locally with this new psql image though:

```Caused by: org.postgresql.util.PSQLException: FATAL: role "api" does not exist
  Location: File: miscinit.c, Routine: InitializeSessionUserId, Line: 502```

**Comment by fabiocognigni** [comment]
The problem was due to having another PSQL instance running locally. Closing this issue.
