### ISSUE TITLE
Arrays not supported as a top-level model definition

### ISSUE THREAD

**Issue by rlmartin** [apicollective/apibuilder#660]
Example Swagger spec (the "Pets" model definition): https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore.json

We could go two different ways here: a) support this or b) say it is covered by the `[Model]` feature and for simplicity it is not supported.

The argument for (a) would be that it provides an easy alias for referencing arrays of models. This, however, is only really a problem in the Swagger spec. Compare `[Model]` to

```
"type": "array",
"items": {
  "$ref": "#/definitions/Model"
}
```

If we're going to support this, we'll need to add a case clause for `ArrayModel` here: https://github.com/apicollective/apibuilder/blob/master/swagger/src/main/scala/me/apidoc/swagger/Parser.scala#L132

If we're not going to support this, we should call it out here: https://github.com/apicollective/apibuilder/blob/master/SWAGGER.md. We should probably also throw a more descriptive error here: https://github.com/apicollective/apibuilder/blob/master/swagger/src/main/scala/me/apidoc/swagger/Parser.scala#L132

**Comment by mbryzek** [comment]
Thanks @rlmartin - any idea how prevalent this is in swagger specs?

**Comment by rlmartin** [comment]
No idea - though it did come up in this one simple example OpenAPI. Of note: the Swagger Pet Store example does not use this pattern: http://petstore.swagger.io/v2/swagger.json. The only use case I can see is to DRY the definition of `Pets`. In ApiBuilder I think it's pretty clear that `[Model]` is all we'd like to see (it's supported, it's already terse, and it's more readable than referencing a model that may or may not match your expectations of a plural `Model`). Given this, I'm leaning towards not supporting it, documenting it, and making the error message clear. This is a trivial amount of work. If we get pushback, we could always switch to supporting it.

**Comment by rlmartin** [comment]
If I'm understanding you correctly, I think the risk would be that the Swagger export wouldn't match the import (i.e. import with `Pets` defined, but it's simply referred to as an array internally in ApiBuilder. We might not know to elevate `Pets` back to the model definition again).

Another argument against allowing a `Pets` model definition is that since ApiBuilder focuses on the models, `Pet` makes more sense - unless all REST endpoints would be expected to operate on an array. Maybe this is an argument _for_ supporting it? Or just another way of looking at it. We'd at least not want to mix response models, i.e. a `GET` should be for a single id for a `Pet` response, whereas a completely different resource would execute a search that might result in a `Pets` response. Same for `DELETE`, `PUT`, `POST`.

**Comment by mbryzek** [comment]
+1 to the idea of not supporting it, documenting it, and making the error message clear

**Comment by fabiocognigni** [comment]
Correct @rlmartin , in that case Swagger export might not match both the ApiBuilder import and the Swagger original spec: I would be fine with that (I like to think at it as a "REST normalization" :) ) but also I guess this will make automated testing of that part a bit too tricky.

Overall I agree that not supporting this case (and documenting it) is the most robust and effective way to go.
