### ISSUE TITLE
Add Member Page Throws Error

### ISSUE THREAD

**Issue by ruxy** [apicollective/apibuilder#682]
Trying to add a member on https://app.apibuilder.io/{org}/members/add leads to error. 

![screen shot 2017-09-01 at 1 08 01 pm](https://user-images.githubusercontent.com/193910/29980184-a4a31884-8f16-11e7-8d92-abc780c05357.png)

Previously the member asked to join the org however we are not seeing the request on https://app.apibuilder.io/{org}/members either.

**Comment by mbryzek** [comment]
would you mind retrying? have confirmed works in my org (I'm not an admin of yours) - also timing leads me to think it was related to a deploy that maybe webapp made it to production before the api endpoint

**Comment by ruxy** [comment]
I think I figured out the issue... I have an admin account in the legacy sign-in but my github account is a member, not an admin. I think that's where that issue came from. All is well now, thank you!
