### ISSUE TITLE
Union types with common fields

### ISSUE THREAD

**Issue by fabiocognigni** [apicollective/apibuilder#687]
Currently there's no way in the api.json syntax to share common fields across all the model types of a Union: *common fields* need to be *repeated* in the definition of all model types. Then, the code generated consists always of an "empty" sealed base trait (/ interface) with all case classes that extend from it repeating all fields.

It'd be nice to have the ability to share fields across all the model types of a union and have the code generated with a shared base-trait/abstract class containing the common fields: this would make writing the code that handles these models much easier (avoid lots of type matching / casting when just need to access common fields).

Two possible ways of supporting this:
1. add a `fields` property to the union declaration in api.json and have code generators reading from that to generate the base trait / abstract class for all the union types;
2. leave api.json syntax as it is and have the generators checking for common fields (_all union types are models and all have a subset of fields with same name and type_) and generating a base trait/class with them when found.

**Comment by mbryzek** [comment]
related to https://github.com/apicollective/apibuilder/issues/441

I think the best path forward is to introduce a new top level entity named "interfaces" that would contain a list of fields.

Then you could add interfaces to each union type. Apidoc would then validate that each interface was in fact implemented by each of the types - allowing us to generate code with the interfaces applied (e.g. traits in scala).

The one option question is how to clearly indicate that a particular model should inherit the fields from an interface - do they get prepended? appended? simpler is to validate that the interface is in fact implemented but this doesn't solve for the duplication in the spec.

**Comment by fabiocognigni** [comment]
Didn't notice there was already an issue on this topic: thanks for pointing that out.

I like the idea of a new top level entity "interfaces" or "mixins": that could the be used for regular models too. I'd probably express this by adding a property "extends" to the models, with the list of interfaces/mixins declared at top level (being aware that this will mean implementing a mini-compiler that checks that same field name is not inherited from 2 different interfaces/mixins and not allowing interfaces extending other interfaces that would mean dealing also with the diamond problem).

**Comment by gheine** [comment]
I'd love to move this forward. I think this would work: Add new top level "interfaces" that contain fields. Models can extend 0 or more interfaces. Unions can also extend 0 or more interfaces. In the case of unions, api builder validates that all union types are (a) model types and (b) actually extend all of the union's interfaces. Thoughts?

**Comment by fabiocognigni** [comment]
Unless I'm missing something, it seems to me redundant to have "interfaces" for unions too. Couldn't we allow **only models** to extend "interfaces" (and avoid check (b) ) ? This way, the fact that model types have common interfaces will remain transparent to the union and you could also have, for example, a union of 3 model types where 2 of them have a common interface, while the other one is a completely different model.

This is mostly inspired on how currently this is done in OpenAPI/Swagger with `allOf` (inheritance of model properties) and `discriminator` (the union type in ApiBuilder).

**Comment by gheine** [comment]
Isn't (part of) the motivation here to be able to have a common base type (or several base types) that all members of the union type adhere to? In that case, rather than inferring the type from the union members I'd much prefer to be explicit about it. 

For the scala code generators, the union base trait can extend the defined interfaces (traits) and the "UnknownUnion" type would also expose these.

**Comment by gheine** [comment]
The way it is at the moment:

```
trait MyUnion
case class MemberOne(s: String, i: Int) extends MyUnion
case class MemberTwo(s: String, d: Double) extends MyUnion
case class MyUnionUnknown(d: Description) extends MyUnion
```

With just models extending interfaces:
```
trait MyInterface {
  def s: String
}
trait MyUnion
case class MemberOne(override s: String, i: Int) extends MyInterface with MyUnion
case class MemberTwo(override s: String, d: Double) extends MyInterface with MyUnion
case class MyUnionUnknown(d: Description) extends MyUnion
```
With models and unions extending interfaces:
```
trait MyInterface {
  def s: String
}
trait MyUnion extends MyInterface
case class MemberOne(override s: String, i: Int) extends MyInterface with MyUnion
case class MemberTwo(override s: String, d: Double) extends MyInterface with MyUnion
case class MyUnionUnknown(d: Description, override s: String) extends MyInterface with MyUnion
```

**Comment by gheine** [comment]
Only in the last case, can I access "s" without having to know what exact union type I have.

The way it is at the moment:
```
val union: MyUnion = ???
val s: String = union match {
  case MemberOne(s, _) => s
  case MemberTwo(s, _) => s
  case _ => throw...
```
With just models extending interfaces:
```
val union: MyUnion = ???
val s: String = union match {
  case m: MyInterface => m.s
  case _ => throw...
```
With models and unions extending interfaces:
```
val union: MyUnion = ???
val s: String = union.s
```

**Comment by fabiocognigni** [comment]
I had a slight preference for not repeating the interface declaration in the spec at the union level and infer the common interfaces for the union type in the generated code but I I'd be fine with declaring them in the union spec too.

**Comment by gheine** [comment]
The problem is specifically the "UnionUnknown" type, that catches responses on the client side in a forward-compatible manner. If you infer the base type(s) of the union from the common interfaces of the union members, your "unknown" needs to also implement the inferred base types. But that may not necessarily be what you want. You may want to be able to add new types to the union at some point that do not share the same base types. The only way you can solve that is by making it explicit which types *all* members of the union (including future ones) are expected to implement.

**Comment by mbryzek** [comment]
implemented in https://github.com/apicollective/apibuilder/pull/826
