### ISSUE TITLE
Override "discriminator field" values for Union types

### ISSUE THREAD

**Issue by andreyk0** [apicollective/apibuilder#692]
When modeling 3rd party APIs with Apibuilder it's some times desirable to override default "discriminator field" encoding of union types.

E.g. on a protocol level a particular (perhaps abbreviated) string value may be required but a non-abbreviated model name may be a better choice on the API level.

Perhaps we could add "value" or something to 
https://app.apibuilder.io/doc/apiJson#unionType

**Comment by mbryzek** [comment]
Agreed! This would be super useful - backwards compatible and likely very straightforward

**Comment by gheine** [comment]
👍

**Comment by gheine** [comment]
The same could work for enum values.

**Comment by mbryzek** [comment]
I'm very bullish on these enhancements. Current Proposal (pls correct if wrong!):

  - for union types, add a field named `discriminator_value` which is optional and will default to the type name of the model (current behavior)

when deserializing/serializing, lookup the model based on discriminator value

  - for enum types, add a new field name `value` which is optional and defaults to the type name (current behavior)

In generators, replace the implementation of `toString` on the enums to instead use `.value`

**Comment by gheine** [comment]
Sounds great!

**Comment by andreyk0** [comment]
👍  thanks! Sounds great!

**Comment by mbryzek** [comment]
starting work at https://github.com/apicollective/apibuilder/tree/discriminator-value-issue-692

**Comment by mbryzek** [comment]
These changes are now live with:

  - https://github.com/apicollective/apibuilder/pull/709
  - https://github.com/apicollective/apibuilder/pull/706
