### ISSUE TITLE
Can't add domain to org that has been added to another org

### ISSUE THREAD

**Issue by gheine** [apicollective/apibuilder#694]
I should be able to add a domain to an organization even though that domain is already added to a different API Builder org. Looks like there may be a unique key on domains, where it should be a unique key on the (org, domain) tuple. 

![screen shot 2017-10-11 at 09 51 01](https://user-images.githubusercontent.com/1324352/31430906-2216839c-ae6a-11e7-8106-ec7fa2edfb40.png)

**Comment by mbryzek** [comment]
Updating at https://github.com/apicollective/apibuilder/pull/695
