### ISSUE TITLE
Default union type

### ISSUE THREAD

**Issue by gheine** [apicollective/apibuilder#698]
The union definition should allow to specify which of the union types is the default type. The default type can be deserialized without discriminator value.

This allows transition from non-union types to union types in a backward compatible way.

**Comment by mbryzek** [comment]
FYI - we added support for default a few months ago - need to confirm docs but I believe it is on the union type itself

**Comment by gheine** [comment]
Oh I missed that, thanks @mbryzek. I was looking on the union model type not on the UnionType type.
