### ISSUE TITLE
finer control of `toString` on enums

### ISSUE THREAD

**Issue by ChengGit** [apicollective/apibuilder#775]
Hey guys, I see apibuilder is using adt to represent enums, and `toString` by default is the literal name of the enum's. 
However, in my case I would like to have a configurable `toString` as an optional field in `apibuilder`'s json config, with a default value that's still the literal name of the enum's?

how would you like it?

**Comment by gheine** [comment]
Hi @ChengGit the optional `value` field in the enum value should override the default `toString`. See https://app.apibuilder.io/doc/apiJson#enumValue

**Comment by ChengGit** [comment]
Thanks Gregor @gheine ! thanks for pointing me to the doc!! 
that's exactly what I meant, i will close this thread now:)
