### ISSUE TITLE
http4s 0.19 is displayed on UI despite being missing

### ISSUE THREAD

**Issue by mkows** [apicollective/apibuilder#783]
When clicking on `Http4s 0.19` the following error gets returned:
```
Generator failed with HTTP 404: Unsupported response code[404]. Expected: 200, 409
```

<img width="839" alt="Screen Shot 2019-03-20 at 14 50 14" src="https://user-images.githubusercontent.com/1754664/54704968-b1ce1880-4b33-11e9-839c-d309ef074a0c.png">

It's also not found in `apibuilder-generator`s for http4s:
https://github.com/apicollective/apibuilder-generator/blob/202386a1bbd7bfe89849aef3a7260bd0b08716b1/scala-generator/src/main/scala/models/generator/ScalaClientMethodConfig.scala#L199

**Comment by mkows** [comment]
As per
https://github.com/apicollective/apibuilder-generator/blob/ddbc94b40c47afe2da53f2e7ff2e12dcc4f9c9fe/generator/app/controllers/Generators.scala#L385

http4s ver. 0.19 should not be listed https://app.apibuilder.io/generators/

**Comment by gheine** [comment]
Deleted the generator
