### ISSUE TITLE
Create a tutorial for apibuilder setup (+ Update the docker files to workable apibuilder)

### ISSUE THREAD

**Issue by Dressi** [apicollective/apibuilder#812]
Dear all,
I tried to run the apibuilder from the attached docker files, but I couldn't do that.
I tried many ways and the instructions from here: https://github.com/apicollective/apibuilder/blob/master/DEVELOPER.md, but I couldn't start a self-hosted version from my docker.
The current last issue, it requires some amazon S3 authentication, but I didn't find any related configuration where can I set that and I still don't understand why it's needed for apibuilder.

Anyone has a working Docker setup or a good tutorial how can I setup and run an apibuilder ?

**Comment by benwaffle** [comment]
There's no tutorial, but you can use the instance at https://app.apibuilder.io

**Comment by mkows** [comment]
Hey @Dressi , not sure if are just looking for a dockerized version, or would just running locally do for you. In case the latter is fine, here are steps that worked for me (assuming you have `docker` and `sbt`):

# Step 0.
Checkout (`git clone`) the following repos:
https://github.com/apicollective/apibuilder (with api and UI)
https://github.com/apicollective/apibuilder-generator (with code generators)

```
# Step 1. Run dockerized DB
docker run -d -p 5432:5432 flowcommerce/apibuilder-postgresql:latest

# Step 2:
## within apibuilder repo (cd apibuilder)
sbt 'api / run 9001'
sbt 'app / run'

cd /hbc/apibuilder-generator && sbt 'generator / run 9002'

Login with http://localhost:9000/login/dev 
In http://localhost:9000/generators add service url: http://localhost:9002

**Comment by Dressi** [comment]
Thank you for your answer.
It's also useful for me.
My goal was to run everything from docker only,
I could do it with small changes: https://github.com/Dressi/apibuilder/pull/1 . I know it's a hack, but It's my first try only and I don't have experience in java and scala yet.
