### ISSUE TITLE
Add schema to https://www.schemastore.org/json/

### ISSUE THREAD

**Issue by asumner** [apicollective/apibuilder#835]
Hi All

Is there any reason why we don't add the API.JSON schema to https://www.schemastore.org/json/ so that we can reference it in Visual Studio code to get intellisense?

Thanks
Anthony

**Comment by gheine** [comment]
Hi, no reason other than that nobody has asked for it so far. Would you be able to add the schema?

**Comment by mbryzek** [comment]
good idea!

**Comment by mikeluby** [comment]
@asumner I've created the schemastore PR https://github.com/SchemaStore/schemastore/pull/1239. Hopefully it's helpful

**Comment by benwaffle** [comment]
That PR was merged. Can we close this issue?

**Comment by benwaffle** [comment]
Add `  "$schema": "https://json.schemastore.org/apibuilder.json",` to the beginning of any API spec to get great autocompletion in your editor.
