### ISSUE TITLE
Swagger: path definition ignored when unit returned in 2xx response

### ISSUE THREAD

**Issue by JennyLeahy** [apicollective/apibuilder#877]
ApiBuilder silently ignored the path definition when unit returned in 2xx response.

```
swagger: '2.0'
info:
  title: JENNYTEST
  version: '1.0'
paths:
  /test:
    put:
      description: a test endpoint
      consumes:
        - application/json
      parameters:
        - in: body
          schema:
            $ref: '#/definitions/TestRequest'
          required: true
          description:  test
      responses:
        '204':
          description: Success Response
        default:
          description: Error
definitions:
  TestRequest:
    type: object
    properties:
      message:
        type: string

```

**Comment by mbryzek** [comment]
@JennyLeahy Thanks for reporting this bug. I was able to reproduce here. API Builder requires a resource to be based on a model and in this case we have no model and therefore there was no resource created.

I'm not 100% sure of the solution, but have opened a patch to create a "placeholder" model and resource for this situation which results in correctly defining the resource in API Builder. PR is at:

https://github.com/apicollective/apibuilder/pull/878

Would you mind taking a look and sharing your thoughts on the approach?
